# -*- coding: utf-8 -*-
"""updater.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hd-KmJu2hH1Op3zj-D4uS6kHEeaT8kX5
"""
#libraries needed for this project

import time
from datetime import datetime
import full_spectre
import agromet_scraper
import shoa_scraper

while True:

    if 1 < int(datetime.now().strftime("%H")) < 23 and int(datetime.now().strftime("%M")) == 5:
        try:
            print("Iniciando actualización 'Radiación Puerto Varas' al servidor: " + str(datetime.now())[:16])
            full_spectre.maxradiation()
            print("Actualización completada a las: " + str(datetime.now())[:16])
        except Exception as error:
            print("Ha ocurrido un error durante la lectura del radiómetro:")
            print(error)

        print("Iniciando actualización 'Radiación Regional' al servidor: " + str(datetime.now())[:16])
        try:
            agromet_scraper.upload()
            print("Actualización agromet completada a las: " + str(datetime.now())[:16])
            print("-----------------------------------------------------------------------")
        except Exception as error:
            print("Ha ocurrido un error conectando a Agrometeorología:")
            print(error)
        
        try:
            print("Iniciando Actualización del Espectro Radiometro al servidor "+ str(datetime.now())[:16])
            full_spectre.insert_espectro()
            print("Actualización  del Espectro Radiometro completada a las: " + str(datetime.now())[:16])
         
        except Exception as error:
            print("Ha ocurrido un error actualizando el espectro:")
            print(error)
        try:
            print("Iniciando Actualización SHOA al servidor "+ str(datetime.now())[:16])
            shoa_scraper.main()
            print("Actualización  SHOA completada a las: " + str(datetime.now())[:16])
         
        except Exception as error:
            print("Ha ocurrido un error actualizando datos SHOA:")
            print(error)
        
        time.sleep(60)

    else:
        time.sleep(30)
